/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;

import business.Product;
import business.ProductCatalog;
import java.awt.CardLayout;
import java.awt.Image;
import java.util.Arrays;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Parth
 */
public class VendorCheck extends javax.swing.JPanel {

    /**
     * Creates new form VendorCheck
     */
    private JPanel userProcessContainer;
    private ProductCatalog productCatalog;
    
    
    public VendorCheck(JPanel userProcessContainer, ProductCatalog productCatalog) {
        initComponents();
        this.productCatalog=productCatalog;
        this.userProcessContainer=userProcessContainer;
   hpLabel.setIcon(new ImageIcon(new ImageIcon("hplogo.png").getImage().getScaledInstance(100, 100, Image.SCALE_DEFAULT)));
   dellLabel.setIcon(new ImageIcon(new ImageIcon("Dell_Logo.png").getImage().getScaledInstance(100, 100, Image.SCALE_DEFAULT)));
   appleLabel.setIcon(new ImageIcon(new ImageIcon("applelogo.png").getImage().getScaledInstance(100, 100, Image.SCALE_DEFAULT)));
   lenovoLabel.setIcon(new ImageIcon(new ImageIcon("lenovologo.jpg").getImage().getScaledInstance(100, 100, Image.SCALE_DEFAULT)));
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnAccess = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        back3Button = new javax.swing.JButton();
        hpRadio = new javax.swing.JRadioButton();
        lenovoRadio = new javax.swing.JRadioButton();
        dellRadio = new javax.swing.JRadioButton();
        appleRadio = new javax.swing.JRadioButton();
        passTextField = new javax.swing.JPasswordField();
        hpLabel = new javax.swing.JLabel();
        dellLabel = new javax.swing.JLabel();
        lenovoLabel = new javax.swing.JLabel();
        appleLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 153));

        btnAccess.setBackground(new java.awt.Color(0, 0, 0));
        btnAccess.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnAccess.setForeground(new java.awt.Color(255, 255, 255));
        btnAccess.setText("Give access");
        btnAccess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccessActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Password");

        back3Button.setBackground(new java.awt.Color(0, 0, 0));
        back3Button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        back3Button.setForeground(new java.awt.Color(255, 255, 255));
        back3Button.setText("<<Back");
        back3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back3ButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(hpRadio);
        hpRadio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        hpRadio.setText("Hewlett Packard");

        buttonGroup1.add(lenovoRadio);
        lenovoRadio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lenovoRadio.setText("Lenovo");
        lenovoRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lenovoRadioActionPerformed(evt);
            }
        });

        buttonGroup1.add(dellRadio);
        dellRadio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dellRadio.setText("Dell");
        dellRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dellRadioActionPerformed(evt);
            }
        });

        buttonGroup1.add(appleRadio);
        appleRadio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        appleRadio.setText("Apple");
        appleRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appleRadioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(back3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(265, 265, 265))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAccess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(passTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hpRadio)
                                    .addComponent(appleRadio)
                                    .addComponent(hpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(279, 279, 279))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(appleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(288, 288, 288)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lenovoRadio, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(dellRadio)
                            .addComponent(lenovoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dellLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(255, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(back3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hpRadio)
                            .addComponent(dellRadio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hpLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(dellLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(lenovoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(appleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appleRadio)
                    .addComponent(lenovoRadio))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(btnAccess, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAccessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccessActionPerformed

        char[] input=passTextField.getPassword();
        char[] pass={'n','a','n'};
        if(Arrays.equals(pass, input)&&(hpRadio.isSelected()||appleRadio.isSelected()||lenovoRadio.isSelected()||dellRadio.isSelected()))
        {
        
        VendorManageWorkAreaJPanel panel= new VendorManageWorkAreaJPanel(userProcessContainer,  productCatalog);
userProcessContainer.add("VendorManageWorkAreaJPanel", panel);
        CardLayout layout= (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Invalid authorization! Please try again.");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnAccessActionPerformed

    private void back3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back3ButtonActionPerformed

userProcessContainer.remove(this);
CardLayout layout= (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_back3ButtonActionPerformed

    private void lenovoRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lenovoRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lenovoRadioActionPerformed

    private void dellRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dellRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dellRadioActionPerformed

    private void appleRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appleRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_appleRadioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appleLabel;
    private javax.swing.JRadioButton appleRadio;
    private javax.swing.JButton back3Button;
    private javax.swing.JButton btnAccess;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel dellLabel;
    private javax.swing.JRadioButton dellRadio;
    private javax.swing.JLabel hpLabel;
    private javax.swing.JRadioButton hpRadio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lenovoLabel;
    private javax.swing.JRadioButton lenovoRadio;
    private javax.swing.JPasswordField passTextField;
    // End of variables declaration//GEN-END:variables
}
